services:
  # Database Service
  db:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Database Migration and Seeding Service
  db-migrate:
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node scripts/docker-seed.js"

  # Application Service
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      # Mount source code so you don't need to rebuild
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
      - ./scripts:/usr/src/app/scripts
      # Keep uploads directory for file persistence
      - ./uploads:/usr/src/app/uploads
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GOOGLE_CLOUD_PROJECT_ID=${GOOGLE_CLOUD_PROJECT_ID}
      - GOOGLE_CLOUD_KEYFILE=${GOOGLE_CLOUD_KEYFILE}
      - GOOGLE_CLOUD_STORAGE_BUCKET=${GOOGLE_CLOUD_STORAGE_BUCKET}
    depends_on:
      db:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
    command: npm run start:prod

volumes:
  postgres_data: